version: "3.8"

services:
  service:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 9229:9229
    command:
      - node
      - --inspect=0.0.0.0
      - build/client/index.js
