import { ProtoOALightSymbol, ProtoOASymbol } from "@claasahl/spotware-adapter";

const symbols: (ProtoOALightSymbol & ProtoOASymbol)[] = [
  Object.freeze({
    symbolId: 1,
    symbolName: "BTC/EUR",
    baseAssetId: 14,
    quoteAssetId: 4,
    enabled: true,
    symbolCategoryId: 1,
    digits: 2,
    holiday: [],
    pipPosition: 5,
    schedule: [],
  }),
  Object.freeze({
    symbolId: 2,
    symbolName: "EURUSD",
    baseAssetId: 4,
    quoteAssetId: 11,
    enabled: true,
    symbolCategoryId: 2,
    digits: 2,
    holiday: [],
    pipPosition: 5,
    schedule: [],
  }),
  Object.freeze({
    symbolId: 3,
    symbolName: "EURGBP",
    baseAssetId: 4,
    quoteAssetId: 5,
    enabled: false,
    symbolCategoryId: 3,
    digits: 2,
    holiday: [],
    pipPosition: 5,
    schedule: [],
  }),
  Object.freeze({
    symbolId: 4,
    symbolName: "XAGEUR",
    baseAssetId: 12,
    quoteAssetId: 4,
    enabled: false,
    symbolCategoryId: 4,
    digits: 2,
    holiday: [],
    pipPosition: 5,
    schedule: [],
  }),
];
export default symbols;
